spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: leetsh
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.jdbc.lob.non_contexual_creation: true # 에러방지
      hibernate.format_sql: true